files:
  - source: /*.md
    ignore:
      - README.md
    translation: /%locale%/%original_file_name%
  - source: how-to/*md
    ignore:
      - /es/
      - /zh-tw/
      - /zh/
    translation: /%locale%/%original_path%/%original_file_name%
